# Top-level Makefile
# Builds everything: planet, Python interface and CLI interface

CC     = /usr/lib/ggdb
CFLAGS = -Wall -fPIC -std=c++11 -Ilib -Iplanet -Itinyxml2 -fopenmp

# Header-dependency tracking. -MMD -MP make the compiler emit, beside each object, the list of
# headers that object was built from; -include feeds those lists back to make so that touching a
# header rebuilds everything that reads it. This matters more here than in most projects, because
# most of ATSAT's physics lives in headers — TurbulenceSat.h, RadiationSat.h, PrecipitationSat.h,
# PressureSolverSat.h, SaturationAdjustmentSat.h, ChemistrySat.h. Without these lists, editing one
# of them would leave every .o stale and `make` would report success while linking the old code.
#
# They used to be written next to the sources as planet/*.d, lib/*.d and so on, which is 25 files
# of build bookkeeping mixed in with the code. -MF redirects them under $(DEPDIR) instead; the
# tracking is unchanged, the source directories stay clean, and `make clean` removes the tree.
DEPDIR   = build/deps
DEPFLAGS = -MMD -MP -MF $(DEPDIR)/$(@D)/$(@F:.o=.d)


# Common files for the shared lib (libatsat.a)
LIB_OBJ = lib/Array.o lib/Array_2D.o lib/Array_1D.o lib/Config.o lib/Utils.o lib/FFT.o

ATSAT_OBJ = planet/cSaturnModel.o planet/PrintMsg_Sat.o planet/RungeKutta_Sat_Turb.o \
planet/RHS_Sat_Turb.o planet/BC_Sat.o planet/ParaView_Sat.o planet/Thermo_Sat.o \
planet/Pressure_Sat.o planet/InitVelocity_Sat.o planet/InitVariables_Sat.o \
planet/Weather_Sat.o planet/FileIO_Sat.o planet/ConvectiveAdjustmentSat.o 

XML_OBJ = tinyxml2/tinyxml2.o

# Command line objects
ATSAT_CLI_OBJ = cli/sat.o cli/DefaultStream.o

# Because there are so many parameters, many of the files are autogenerated
PARAM_OUTPUTS = planet/cSaturnDefaults.cpp.inc planet/SaturnLoadConfig.cpp.inc \
planet/SaturnParams.h.inc saturn/config_atsat.xml python/saturn_pxd.pxi python/pyatsat.pyx

#copy pyatsat.so from python dir to saturn dir
COPY_FILE = pyatsat.so
TARGET_DIR = saturn

target = $(addprefix $(TARGET_DIR)/,$(COPY_FILE))

all: sat python $(target)

libatsat.a: $(PARAM_OUTPUTS) $(LIB_OBJ) $(ATSAT_OBJ) $(XML_OBJ)
	ar rcs libatsat.a $(LIB_OBJ) $(ATSAT_OBJ) $(XML_OBJ)

sat: libatsat.a $(ATSAT_CLI_OBJ)
	$(CXX) $(CFLAGS) $(ATSAT_CLI_OBJ) -L. -latsat $(LDFLAGS) -o cli/sat

$(PARAM_OUTPUTS): param.py
# explicitly clean dependent files
	rm -f planet/cSaturnModel.o
	python3 param.py

analyze:
	analyze-build make

python: libatsat.a python/pyatsat.so

python/pyatsat.so: python/pyatsat.pyx python/atsat.pxd libatsat.a
	cd python && python3 setup.py build_ext --inplace

# copy pyatsat.so from python dir to saturn dir
$(TARGET_DIR)/pyatsat.so: python/pyatsat.cpython-310-x86_64-linux-gnu.so
	cp $< $@


planet/%.o: planet/%.cpp
	@mkdir -p $(DEPDIR)/planet
	$(CXX) $(CFLAGS) $(DEPFLAGS) -c $< -o $@

lib/%.o: lib/%.cpp
	@mkdir -p $(DEPDIR)/lib
	$(CXX) $(CFLAGS) $(DEPFLAGS) -c $< -o $@

cli/%.o: cli/%.cpp
	@mkdir -p $(DEPDIR)/cli
	$(CXX) $(CFLAGS) $(DEPFLAGS) -c $< -o $@

tinyxml2/%.o: tinyxml2/%.cpp
	@mkdir -p $(DEPDIR)/tinyxml2
	$(CXX) $(CFLAGS) $(DEPFLAGS) -c $< -o $@

%.o: %.cpp
	@mkdir -p $(DEPDIR)/$(@D)
	$(CXX) $(CFLAGS) $(DEPFLAGS) -c $<

# Auto-generated header dependency lists (see DEPFLAGS above). Kept under $(DEPDIR), not beside
# the sources. The leading - on include means "no error if absent", so a clean tree still builds.
ALL_OBJ  = $(LIB_OBJ) $(ATSAT_OBJ) $(XML_OBJ) $(ATSAT_CLI_OBJ)
ALL_DEPS = $(addprefix $(DEPDIR)/,$(ALL_OBJ:.o=.d))
-include $(ALL_DEPS)

.PHONY: clean
clean:
	\rm -vf $(LIB_OBJ) $(ATSAT_OBJ) $(XML_OBJ) $(ATSAT_CLI_OBJ) $(PARAM_OUTPUTS) sat libatsat.a
	\rm -rf $(DEPDIR)
	# stray .d files from before the dependency lists moved under $(DEPDIR)
	\rm -vf planet/*.d lib/*.d cli/*.d tinyxml2/*.d
	\rm -vf python/*.so python/*.o python/pyatsat.cpp
	\rm -rf python/build/
