# Top-level Makefile
# Builds everything: planet, Python interface and CLI interface

CC     = /usr/lib/ggdb
CFLAGS = -Wall -fPIC -std=c++11 -Ilib -Iplanet -Itinyxml2 -fopenmp -MMD -MP


# Common files for the shared lib (libatsat.a)
LIB_OBJ = lib/Array.o lib/Array_2D.o lib/Array_1D.o lib/Config.o lib/Utils.o lib/FFT.o

ATSAT_OBJ = planet/cSaturnModel.o planet/PrintMsg_Sat.o planet/RungeKutta_Sat_Turb.o \
planet/RHS_Sat_Turb.o planet/BC_Sat.o planet/ParaView_Sat.o planet/Thermo_Sat.o \
planet/Pressure_Sat.o planet/InitVelocity_Sat.o planet/InitVariables_Sat.o \
planet/Weather_Sat.o planet/FileIO_Sat.o planet/ConvectiveAdjustmentSat.o 

XML_OBJ = tinyxml2/tinyxml2.o

# Command line objects
ATSAT_CLI_OBJ = cli/sat.o cli/DefaultStream.o

# Because there are so many parameters, many of the files are autogenerated
PARAM_OUTPUTS = planet/cSaturnDefaults.cpp.inc planet/SaturnLoadConfig.cpp.inc \
planet/SaturnParams.h.inc saturn/config_atsat.xml python/saturn_pxd.pxi python/pyatsat.pyx

#copy pyatsat.so from python dir to saturn dir
COPY_FILE = pyatsat.so
TARGET_DIR = saturn

target = $(addprefix $(TARGET_DIR)/,$(COPY_FILE))

all: sat python $(target)

libatsat.a: $(PARAM_OUTPUTS) $(LIB_OBJ) $(ATSAT_OBJ) $(XML_OBJ)
	ar rcs libatsat.a $(LIB_OBJ) $(ATSAT_OBJ) $(XML_OBJ)

sat: libatsat.a $(ATSAT_CLI_OBJ)
	$(CXX) $(CFLAGS) $(ATSAT_CLI_OBJ) -L. -latsat $(LDFLAGS) -o cli/sat

$(PARAM_OUTPUTS): param.py
# explicitly clean dependent files
	rm -f planet/cSaturnModel.o
	python3 param.py

analyze:
	analyze-build make

python: libatsat.a python/pyatsat.so

python/pyatsat.so: python/pyatsat.pyx python/atsat.pxd libatsat.a
	cd python && python3 setup.py build_ext --inplace

# copy pyatsat.so from python dir to saturn dir
$(TARGET_DIR)/pyatsat.so: python/pyatsat.cpython-310-x86_64-linux-gnu.so
	cp $< $@


planet/%.o: planet/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

lib/%.o: lib/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

cli/%.o: cli/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

tinyxml2/%.o: tinyxml2/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

%.o: %.cpp
	$(CXX) $(CFLAGS) -c $<

# Auto-generated header dependency files (produced by -MMD -MP)
ALL_DEPS = $(LIB_OBJ:.o=.d) $(ATSAT_OBJ:.o=.d) $(XML_OBJ:.o=.d) $(ATSAT_CLI_OBJ:.o=.d)
-include $(ALL_DEPS)

.PHONY: clean
clean:
	\rm -vf $(LIB_OBJ) $(ATSAT_OBJ) $(XML_OBJ) $(ATSAT_CLI_OBJ) $(PARAM_OUTPUTS) sat libatsat.a $(ALL_DEPS)
	\rm -vf python/*.so python/*.o python/pyatsat.cpp
	\rm -rf python/build/
