# pxd files
# THIS FILE IS AUTOMATICALLY GENERATED BY param.py
# ANY CHANGES WILL BE OVERWRITTEN AT COMPILE TIME
from libcpp.vector cimport vector
cdef extern from "cSaturnModel.h":
    cppclass cSaturnModel:
        cSaturnModel() except +  # NB! std::bad_alloc will be converted to MemoryError
        void LoadConfig(const char *filename)
        void Run()
        # common section
        string bathymetry_path
        string BathymetrySuffix
        bool verbose
        string output_path
        bool paraview_flag
        # saturn section
        int nm
        int checkpoint
        int panorama_print
        double Coriolis
        double centrifugal
        double buoyancy
        double chemical_reaction
        double epsres
        double L_atm
        double tropopause_pole
        double tropopause_equator
        double re
        double ec
        double ep
        double hp
        double lv
        double ls
        double cp_l
        double pr
        double g
        double omega
        double gam
        double u_0
        double r_0_water
        double ua
        double va
        double wa
        double pa
        double ca
        double ta
        double t_ref
        double t_equator
        double t_pole
        double p_ref
        double R_ref
        double t_tropopause
        double t_react_onset
        double p_tropopause
        double h2_tropopause
        double he_tropopause
        double h2o_tropopause
        double h2s_tropopause
        double nh3_tropopause
        double nh4sh_tropopause
        double ch4_tropopause
